# Generated by Django 5.2.3 on 2025-08-26 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tenant_description_tenant_email_tenant_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the action. Null if system/unknown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_logs', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='The user affected by the action.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
