# Generated by Django 5.2.3 on 2026-01-31 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_username', models.CharField(db_index=True, help_text='Username for RADIUS authentication', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('data_limit_mb', models.PositiveIntegerField(blank=True, help_text='Data limit in megabytes (null = unlimited)', null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (null = unlimited)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Subscription expiry date (null = never expires)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='subscribers_tenant__4fb551_idx'), models.Index(fields=['expires_at'], name='subscribers_expires_e12eb2_idx')],
            },
        ),
    ]
