#!/bin/bash

# ITLDS MVP Teardown Script
# Stops and removes all Docker resources

set -e

echo "=========================================="
echo "ITLDS MVP Teardown"
echo "=========================================="

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ $1${NC}"; }
print_error() { echo -e "${RED}✗ $1${NC}"; }

# Parse flags
REMOVE_VOLUMES=false
REMOVE_NETWORK=false
REMOVE_SECRETS=false
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --volumes|-v)
            REMOVE_VOLUMES=true
            shift
            ;;
        --network|-n)
            REMOVE_NETWORK=true
            shift
            ;;
        --secrets|-s)
            REMOVE_SECRETS=true
            shift
            ;;
        --all|-a)
            REMOVE_VOLUMES=true
            REMOVE_NETWORK=true
            REMOVE_SECRETS=true
            shift
            ;;
        --yes|-y)
            NON_INTERACTIVE=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--volumes|-v] [--network|-n] [--secrets|-s] [--all|-a] [--yes|-y]"
            exit 1
            ;;
    esac
done

# Confirmation prompt
if [ "$NON_INTERACTIVE" = false ]; then
    echo "This will stop and remove all containers."
    [ "$REMOVE_VOLUMES" = true ] && echo "⚠ Volumes will be DELETED (all data will be lost)"
    [ "$REMOVE_NETWORK" = true ] && echo "⚠ Network 'web' will be removed"
    [ "$REMOVE_SECRETS" = true ] && echo "⚠ Secrets will be deleted"
    echo ""
    read -p "Are you sure? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_warning "Teardown cancelled"
        exit 0
    fi
fi

# Stop containers
echo "Stopping containers..."
if [ "$REMOVE_VOLUMES" = true ]; then
    docker compose down -v
    print_success "Containers stopped and volumes removed"
else
    docker compose down
    print_success "Containers stopped (volumes preserved)"
fi

# Clean up generated files
echo "Removing generated configuration files..."
# Remove Traefik dynamic config (will be regenerated by setup.sh)
if [ -f "KoolFlows/traefik/dynamic/config.yml" ]; then
    rm -f KoolFlows/traefik/dynamic/config.yml
    print_success "Removed Traefik dynamic config"
fi

# Remove QueWall generated realm file
if [ -f "QueWall/keycloak/realm-export-generated.json" ]; then
    rm -f QueWall/keycloak/realm-export-generated.json
    print_success "Removed QueWall realm configuration"
fi

# Remove network
if [ "$REMOVE_NETWORK" = true ]; then
    echo "Removing Docker network..."
    if docker network inspect web > /dev/null 2>&1; then
        docker network rm web
        print_success "Network 'web' removed"
    else
        print_warning "Network 'web' does not exist"
    fi
fi

# Remove secrets
if [ "$REMOVE_SECRETS" = true ]; then
    echo "Removing secrets..."
    if [ -d "secrets" ]; then
        rm -f secrets/*.txt
        print_success "Secrets removed"
    fi
fi

# Clean up data directories
if [ "$REMOVE_VOLUMES" = true ]; then
    echo "Cleaning local data directories..."

    # KoolFlows
    [ -d "KoolFlows/crowdsec/data" ] && rm -rf KoolFlows/crowdsec/data/* && print_success "CrowdSec data cleared"

    # PeSquel
    [ -d "PeSquel/postgres/data" ] && rm -rf PeSquel/postgres/data/* && print_success "PostgreSQL data cleared"
    [ -d "PeSquel/pgadmin/data" ] && rm -rf PeSquel/pgadmin/data/* && print_success "pgAdmin data cleared"
fi

echo ""
echo "=========================================="
echo "Teardown Complete!"
echo "=========================================="
echo ""

if [ "$REMOVE_VOLUMES" = false ]; then
    echo "💡 To remove volumes as well, run:"
    echo "   ./teardown.sh --volumes"
fi

if [ "$REMOVE_NETWORK" = false ]; then
    echo "💡 To remove network, run:"
    echo "   ./teardown.sh --network"
fi

if [ "$REMOVE_SECRETS" = false ]; then
    echo "💡 To remove secrets, run:"
    echo "   ./teardown.sh --secrets"
fi

echo ""
echo "💡 To remove everything, run:"
echo "   ./teardown.sh --all"
echo ""
echo "To start fresh, run: ./setup.sh"
echo ""

print_success "All specified resources have been cleaned up"
