import type { Metadata } from "next";
import "../globals.css";
import { languages, type Language } from "../lib/i18n/settings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lng } = await params as { lng: Language };

  return (
    <html lang={lng}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
