# Generated by Django 5.2.3 on 2025-08-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('requires_payment', models.BooleanField(default=True)),
                ('requires_invoice', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('daily_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_data_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interval', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='month', max_length=10)),
                ('trial_period_days', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=128, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='payment_gateway.plan')),
            ],
            options={
                'ordering': ['plan__name', 'amount'],
                'unique_together': {('plan', 'currency', 'interval', 'amount')},
            },
        ),
    ]
